--
-- PostgreSQL database dump
--

\restrict 29GBjWIChDLUofhmfaZj3iw1ZeExSJ5x6KTLitnd2ej0yPOB6RUnK8q68A4WmRG

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

-- Started on 2026-09-21 19:29:20

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 238 (class 1259 OID 122937)
-- Name: analisis_imagen; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.analisis_imagen (
    id bigint NOT NULL,
    estado character varying(255) NOT NULL,
    fecha_procesamiento timestamp(6) without time zone,
    fecha_subida timestamp(6) without time zone NOT NULL,
    mensaje_error character varying(255),
    resultado_json text,
    ruta_imagen character varying(255) NOT NULL,
    proyecto_id bigint,
    usuario_id bigint NOT NULL,
    CONSTRAINT analisis_imagen_estado_check CHECK (((estado)::text = ANY ((ARRAY['SUBIDA'::character varying, 'PROCESANDO'::character varying, 'COMPLETADA'::character varying, 'ERROR'::character varying])::text[])))
);


ALTER TABLE public.analisis_imagen OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 122936)
-- Name: analisis_imagen_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.analisis_imagen ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.analisis_imagen_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 106498)
-- Name: bitacora; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.bitacora (
    id bigint NOT NULL,
    accion character varying(255),
    descripcion character varying(255),
    fecha_hora timestamp(6) without time zone,
    proyecto_id bigint,
    usuario_id bigint NOT NULL
);


ALTER TABLE public.bitacora OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 106497)
-- Name: bitacora_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.bitacora ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bitacora_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 106579)
-- Name: diagrama; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.diagrama (
    id bigint NOT NULL,
    fecha_actualizacion timestamp(6) without time zone NOT NULL,
    fecha_creacion timestamp(6) without time zone NOT NULL,
    modelo_json text,
    nombre character varying(255) NOT NULL,
    version bigint NOT NULL,
    proyecto_id bigint NOT NULL,
    activo boolean DEFAULT true NOT NULL
);


ALTER TABLE public.diagrama OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 106578)
-- Name: diagrama_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.diagrama ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.diagrama_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 106647)
-- Name: invitacion_proyecto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.invitacion_proyecto (
    id bigint NOT NULL,
    estado character varying(255) NOT NULL,
    fecha_creacion timestamp(6) without time zone NOT NULL,
    fecha_expiracion timestamp(6) without time zone,
    token character varying(255) NOT NULL,
    anfitrion_id bigint NOT NULL,
    proyecto_id bigint NOT NULL,
    usuario_invitado_id bigint NOT NULL,
    CONSTRAINT invitacion_proyecto_estado_check CHECK (((estado)::text = ANY ((ARRAY['PENDIENTE'::character varying, 'ACEPTADA'::character varying, 'RECHAZADA'::character varying])::text[])))
);


ALTER TABLE public.invitacion_proyecto OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 106646)
-- Name: invitacion_proyecto_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.invitacion_proyecto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.invitacion_proyecto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 106508)
-- Name: participante_proyecto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.participante_proyecto (
    id bigint NOT NULL,
    activo boolean,
    fecha_ingreso timestamp(6) without time zone,
    proyecto_id bigint NOT NULL,
    usuario_id bigint NOT NULL
);


ALTER TABLE public.participante_proyecto OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 106507)
-- Name: participante_proyecto_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.participante_proyecto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.participante_proyecto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 106598)
-- Name: permiso; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.permiso (
    id bigint NOT NULL,
    activo boolean NOT NULL,
    codigo character varying(255) NOT NULL,
    descripcion character varying(255),
    nombre character varying(255)
);


ALTER TABLE public.permiso OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 106597)
-- Name: permiso_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.permiso ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.permiso_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 240 (class 1259 OID 122951)
-- Name: peticion_ia; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.peticion_ia (
    id bigint NOT NULL,
    exitoso boolean,
    fecha_peticion timestamp(6) without time zone NOT NULL,
    origen character varying(255) NOT NULL,
    prompt_texto text,
    resultado_json text,
    tokens_usados integer,
    diagrama_id bigint,
    usuario_id bigint NOT NULL,
    CONSTRAINT peticion_ia_origen_check CHECK (((origen)::text = ANY ((ARRAY['TEXTO_WEB'::character varying, 'VOZ_MOBILE'::character varying])::text[])))
);


ALTER TABLE public.peticion_ia OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 122950)
-- Name: peticion_ia_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.peticion_ia ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.peticion_ia_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 106517)
-- Name: proyecto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.proyecto (
    id bigint NOT NULL,
    activo boolean,
    descripcion character varying(255),
    fecha_actualizacion timestamp(6) without time zone,
    fecha_creacion timestamp(6) without time zone,
    nombre character varying(255),
    anfitrion_id bigint
);


ALTER TABLE public.proyecto OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 106516)
-- Name: proyecto_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.proyecto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.proyecto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 106526)
-- Name: rol; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.rol (
    id bigint NOT NULL,
    activo boolean,
    descripcion character varying(255),
    fecha_creacion timestamp(6) without time zone,
    nombre character varying(255)
);


ALTER TABLE public.rol OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 106525)
-- Name: rol_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.rol ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rol_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 106608)
-- Name: rol_permiso; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.rol_permiso (
    rol_id bigint NOT NULL,
    permiso_id bigint NOT NULL
);


ALTER TABLE public.rol_permiso OWNER TO postgres;

--
-- TOC entry 242 (class 1259 OID 122964)
-- Name: sincronizacion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sincronizacion (
    id bigint NOT NULL,
    estado_resolucion character varying(255) NOT NULL,
    fecha_colision timestamp(6) without time zone NOT NULL,
    modelo_json_cliente text NOT NULL,
    version_cliente bigint,
    version_servidor bigint,
    diagrama_id bigint NOT NULL,
    usuario_id bigint NOT NULL,
    CONSTRAINT sincronizacion_estado_resolucion_check CHECK (((estado_resolucion)::text = ANY ((ARRAY['PENDIENTE_MERGE'::character varying, 'RESUELTO_CLIENTE'::character varying, 'RESUELTO_SERVIDOR'::character varying])::text[])))
);


ALTER TABLE public.sincronizacion OWNER TO postgres;

--
-- TOC entry 241 (class 1259 OID 122963)
-- Name: sincronizacion_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sincronizacion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sincronizacion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 106535)
-- Name: usuario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuario (
    id bigint NOT NULL,
    activo boolean,
    apellido character varying(255),
    correo character varying(255) NOT NULL,
    fecha_actualizacion timestamp(6) without time zone,
    fecha_creacion timestamp(6) without time zone,
    nombre character varying(255),
    password character varying(255),
    rol_id bigint
);


ALTER TABLE public.usuario OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 106534)
-- Name: usuario_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.usuario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 106627)
-- Name: usuario_permiso; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuario_permiso (
    usuario_id bigint NOT NULL,
    permiso_id bigint NOT NULL
);


ALTER TABLE public.usuario_permiso OWNER TO postgres;

--
-- TOC entry 5141 (class 0 OID 122937)
-- Dependencies: 238
-- Data for Name: analisis_imagen; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.analisis_imagen (id, estado, fecha_procesamiento, fecha_subida, mensaje_error, resultado_json, ruta_imagen, proyecto_id, usuario_id) FROM stdin;
\.


--
-- TOC entry 5123 (class 0 OID 106498)
-- Dependencies: 220
-- Data for Name: bitacora; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.bitacora (id, accion, descripcion, fecha_hora, proyecto_id, usuario_id) FROM stdin;
1	CREAR_PROYECTO	Creó el proyecto Proyecto IA	2026-09-17 17:13:30.376925	1	1
2	CAMBIAR_ESTADO_PROYECTO	Desactivó el proyecto Proyecto IA	2026-09-17 17:16:41.214086	1	1
3	CREAR_DIAGRAMA	Creó el diagrama: Diagrama Principal	2026-09-17 17:58:06.339429	1	1
4	CREAR_PROYECTO	Creó el proyecto Biblioteca	2026-09-17 18:09:20.512917	2	1
5	CREAR_DIAGRAMA	Creó el diagrama: personal	2026-09-17 18:09:34.342275	2	1
6	CREAR_USUARIO	Creó el usuario alejandro@gmail.com	2026-09-18 10:42:02.310824	\N	1
7	ELIMINAR_USUARIO	Eliminó el usuario newuser@example.com	2026-09-18 11:09:48.712673	\N	1
8	CREAR_USUARIO	Creó el usuario nick@gmail.com	2026-09-18 11:11:10.175439	\N	1
9	ELIMINAR_USUARIO	Eliminó el usuario nick@gmail.com	2026-09-18 11:13:30.886847	\N	1
10	CREAR_USUARIO	Creó el usuario lulu@gmail.com	2026-09-18 11:14:34.324471	\N	1
11	CREAR_USUARIO	Creó el usuario pepe@gmail.com	2026-09-18 11:15:57.854042	\N	1
12	ELIMINAR_USUARIO	Eliminó el usuario pepe@gmail.com	2026-09-18 11:21:16.200227	\N	1
13	CREAR_USUARIO	Creó el usuario linda@gmail.com	2026-09-18 11:21:35.399185	\N	1
14	ELIMINAR_USUARIO	Eliminó el usuario lulu@gmail.com	2026-09-18 11:21:42.519616	\N	1
15	MODIFICAR_USUARIO	Modificó el usuario alison@gmail.com	2026-09-18 11:23:43.000331	\N	1
16	MODIFICAR_USUARIO	Modificó el usuario alejandro@gmail.com	2026-09-18 11:23:51.028521	\N	1
17	MODIFICAR_USUARIO	Modificó el usuario alejandro@gmail.com	2026-09-18 11:24:25.059315	\N	1
18	CAMBIAR_ESTADO_USUARIO	Desactivó el usuario linda@gmail.com	2026-09-18 11:30:42.195428	\N	1
19	MODIFICAR_USUARIO	Modificó el usuario linda@gmail.com	2026-09-18 11:30:59.104658	\N	1
20	MODIFICAR_USUARIO	Modificó el usuario linda@gmail.com	2026-09-18 11:31:43.54172	\N	1
21	CAMBIAR_ESTADO_USUARIO	Activó el usuario linda@gmail.com	2026-09-18 11:31:53.580662	\N	1
22	CAMBIAR_ESTADO_USUARIO	Desactivó el usuario linda@gmail.com	2026-09-18 11:32:04.550505	\N	1
23	CREAR_ROL	Creó el rol CLIENTE	2026-09-18 12:27:05.08669	\N	1
24	CAMBIAR_ROL_USUARIO	Cambió rol del usuario linda@gmail.com a CLIENTE	2026-09-18 12:27:32.379904	\N	1
25	MODIFICAR_PERMISOS_USUARIO	Actualizó permisos de linda@gmail.com	2026-09-18 12:27:32.4069	\N	1
26	CREAR_DIAGRAMA	Creó el diagrama: inventario	2026-09-18 13:03:08.188385	2	1
27	CAMBIAR_ESTADO_PROYECTO	Desactivó el proyecto Biblioteca	2026-09-18 13:03:35.345415	2	1
28	CAMBIAR_ESTADO_PROYECTO	Activó el proyecto Biblioteca	2026-09-18 13:03:38.877072	2	1
29	CAMBIAR_ESTADO_PROYECTO	Activó el proyecto Proyecto IA	2026-09-18 13:03:43.165392	1	1
30	CAMBIAR_ESTADO_PROYECTO	Desactivó el proyecto Proyecto IA	2026-09-18 13:53:20.670599	1	1
31	CAMBIAR_ESTADO_PROYECTO	Activó el proyecto Proyecto IA	2026-09-18 13:53:24.463849	1	1
32	CREAR_DIAGRAMA	Creó el diagrama: Inventario	2026-09-18 14:04:11.85115	1	1
33	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-18 21:29:02.653564	2	1
34	MODIFICAR_DIAGRAMA	Modificó el diagrama: inventario	2026-09-18 21:48:24.445511	2	1
35	MODIFICAR_DIAGRAMA	Modificó el diagrama: inventario	2026-09-18 21:49:58.908227	2	1
36	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-18 21:52:21.075689	2	1
37	MODIFICAR_PERMISOS_USUARIO	Actualizó permisos de alison@gmail.com	2026-09-18 22:15:11.547863	\N	1
38	MODIFICAR_PERMISOS_USUARIO	Actualizó permisos de alison@gmail.com	2026-09-18 22:15:22.576369	\N	1
39	MODIFICAR_PERMISOS_USUARIO	Actualizó permisos de alison@gmail.com	2026-09-18 22:16:07.899508	\N	1
40	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-18 22:21:07.223831	2	1
41	MODIFICAR_DIAGRAMA	Modificó el diagrama: inventario	2026-09-18 22:35:53.776069	2	1
42	AGREGAR_PARTICIPANTE	Agregó a alison@gmail.com al proyecto	2026-09-18 22:47:11.762686	2	1
43	INVITAR_PARTICIPANTE	Invitó a alison@gmail.com	2026-09-18 23:19:20.569534	1	1
44	INVITAR_PARTICIPANTE	Invitó a alejandro@gmail.com	2026-09-18 23:21:31.431291	1	1
45	ACEPTAR_INVITACION	Aceptó la invitación al proyecto	2026-09-18 23:21:36.72484	1	3
46	CANCELAR_INVITACION	Canceló la invitación a alejandro@gmail.com	2026-09-18 23:32:57.462918	1	1
47	INVITAR_PARTICIPANTE	Invitó a alejandro@gmail.com	2026-09-18 23:51:58.678001	2	1
48	CANCELAR_INVITACION	Canceló la invitación a alejandro@gmail.com	2026-09-19 00:12:21.995094	2	1
49	INVITAR_PARTICIPANTE	Invitó a alejandro@gmail.com	2026-09-19 00:14:50.127643	2	1
50	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 00:42:54.119716	2	1
51	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 00:51:18.061422	2	1
52	MODIFICAR_DIAGRAMA	Modificó el diagrama: inventario	2026-09-19 01:31:53.086762	2	1
53	MODIFICAR_DIAGRAMA	Modificó el diagrama: inventario	2026-09-19 01:32:22.15296	2	3
54	MODIFICAR_DIAGRAMA	Modificó el diagrama: inventario	2026-09-19 01:36:58.231095	2	1
55	MODIFICAR_DIAGRAMA	Modificó el diagrama: inventario	2026-09-19 01:44:49.240427	2	1
56	MODIFICAR_DIAGRAMA	Modificó el diagrama: inventario	2026-09-19 01:51:53.222947	2	1
57	MODIFICAR_DIAGRAMA	Modificó el diagrama: inventario	2026-09-19 01:56:16.22695	2	1
58	MODIFICAR_DIAGRAMA	Modificó el diagrama: inventario	2026-09-19 01:56:26.700024	2	1
59	MODIFICAR_DIAGRAMA	Modificó el diagrama: inventario	2026-09-19 01:58:34.232529	2	3
60	MODIFICAR_DIAGRAMA	Modificó el diagrama: inventario	2026-09-19 01:58:34.237082	2	1
61	MODIFICAR_DIAGRAMA	Modificó el diagrama: inventario	2026-09-19 01:58:51.991556	2	1
62	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 02:00:54.059795	2	1
63	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 02:00:58.216477	2	1
64	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 02:01:13.234668	2	1
65	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 02:01:27.544365	2	1
66	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 02:01:55.218476	2	1
67	MODIFICAR_DIAGRAMA	Modificó el diagrama: inventario	2026-09-19 02:02:36.202252	2	3
68	MODIFICAR_DIAGRAMA	Modificó el diagrama: inventario	2026-09-19 02:02:39.312253	2	3
69	MODIFICAR_DIAGRAMA	Modificó el diagrama: inventario	2026-09-19 02:02:43.823312	2	3
70	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 02:15:13.375934	2	3
71	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 02:15:24.39633	2	3
72	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 02:15:41.136386	2	1
73	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 02:15:58.01923	2	1
74	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 02:16:09.667918	2	1
76	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 02:17:12.654448	2	1
77	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 02:17:17.219692	2	1
79	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 02:20:51.712813	2	3
80	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 02:21:00.975646	2	1
81	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 02:21:07.52928	2	1
83	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 02:21:22.32769	2	1
84	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 02:33:42.242277	2	1
75	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 02:16:23.940427	2	3
78	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 02:20:49.282842	2	1
82	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 02:21:19.463642	2	1
85	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 02:33:42.267887	2	3
86	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 02:34:41.335116	2	1
87	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 02:34:58.747964	2	3
117	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 10:41:42.074107	2	1
118	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 10:42:01.121325	2	3
119	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 10:42:11.912499	2	3
120	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 10:42:15.659021	2	3
121	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 10:42:16.148609	2	1
122	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 10:42:24.325387	2	1
123	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 10:42:35.147567	2	1
124	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 10:50:15.653193	2	1
125	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 10:50:17.194527	2	3
126	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 10:50:23.839806	2	1
127	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 10:50:28.37822	2	1
128	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 11:23:29.094284	2	1
129	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 11:23:38.805848	2	1
130	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 11:23:52.856449	2	3
131	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 11:23:57.506214	2	3
132	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 11:24:28.953758	2	1
133	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 11:24:32.673622	2	1
134	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 11:24:42.310012	2	3
135	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 11:24:47.833936	2	3
136	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 11:24:52.195733	2	3
137	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 11:24:57.360275	2	1
138	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 11:24:57.393831	2	3
139	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 11:25:34.14486	2	1
140	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 11:25:37.195703	2	3
141	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 11:25:43.716246	2	3
143	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 11:25:55.019428	2	3
144	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 11:25:55.037113	2	1
145	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 11:33:28.108234	2	1
146	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 11:33:28.109232	2	3
147	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 11:33:38.09943	2	1
148	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 11:33:38.10044	2	3
149	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 11:42:27.076944	2	1
150	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 11:42:39.472982	2	3
151	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 11:43:00.703709	2	1
152	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 11:43:48.872495	2	1
153	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 11:43:59.204755	2	1
154	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 11:44:25.510617	2	1
155	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 11:44:55.09051	2	1
156	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 11:45:22.123153	2	1
157	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 11:45:27.416127	2	3
158	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 11:48:37.260116	2	1
159	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 11:49:12.206304	2	3
160	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 11:50:26.291084	2	3
161	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 12:01:16.306216	2	1
162	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 12:03:59.488958	2	1
163	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 12:04:07.752414	2	1
164	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 12:04:11.112386	2	1
165	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 12:04:15.1548	2	1
166	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 12:04:36.834388	2	3
167	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 12:04:40.4275	2	3
168	MODIFICAR_DIAGRAMA	Modificó el diagrama: Diagrama Principal	2026-09-19 12:13:02.981126	1	1
169	MODIFICAR_DIAGRAMA	Modificó el diagrama: Diagrama Principal	2026-09-19 13:16:30.173672	1	1
170	MODIFICAR_DIAGRAMA	Modificó el diagrama: Diagrama Principal	2026-09-19 13:16:35.086655	1	1
171	MODIFICAR_DIAGRAMA	Modificó el diagrama: Diagrama Principal	2026-09-19 13:19:26.087484	1	1
172	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 15:02:04.291504	2	1
173	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 15:02:23.227194	2	1
174	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 15:03:00.48786	2	3
175	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 15:03:10.441937	2	3
176	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 15:03:17.675687	2	3
177	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 15:03:25.095442	2	1
178	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 15:07:17.090835	2	1
179	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 15:07:25.08792	2	1
180	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 15:08:30.095791	2	1
181	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 15:45:27.65822	2	1
182	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 15:45:30.194123	2	1
183	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 15:49:26.236687	2	3
184	MODIFICAR_DIAGRAMA	Modificó el diagrama: personal	2026-09-19 15:49:32.272836	2	3
185	CREAR_DIAGRAMA	Creó el diagrama: veterinaria	2026-09-21 14:24:30.007257	2	1
186	LOGIN	Usuario inició sesión	2026-09-21 17:36:42.168649	\N	1
\.


--
-- TOC entry 5133 (class 0 OID 106579)
-- Dependencies: 230
-- Data for Name: diagrama; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.diagrama (id, fecha_actualizacion, fecha_creacion, modelo_json, nombre, version, proyecto_id, activo) FROM stdin;
4	2026-09-18 14:04:11.805391	2026-09-18 14:04:11.805391	{"clases":[],"relaciones":[]}	Inventario	0	1	t
1	2026-09-19 12:13:03.053049	2026-09-17 17:58:06.300451	{"clases":[{"id":"c1","nombre":"Usuario","estereotipo":"","posicionX":null,"posicionY":null,"atributos":[],"metodos":[]}],"relaciones":[]}	Diagrama Principal	1	1	t
3	2026-09-19 01:51:53.22861	2026-09-18 13:03:08.171393	{"clases":[{"id":"c_dioc1jg","nombre":"Cliente","estereotipo":"","posicionX":-233.008,"posicionY":118.62799999999999,"atributos":[{"id":"sxufcrb","nombre":"ID","tipo":"Long","visibilidad":"private"},{"id":"xilczfy","nombre":"Nombre","tipo":"String","visibilidad":"private"}],"metodos":[]},{"id":"c_ob42cxz","nombre":"Pedido","estereotipo":"","posicionX":153.984,"posicionY":-105.45599999999996,"atributos":[{"id":"iw3w69t","nombre":"ID","tipo":"Long","visibilidad":"private"},{"id":"mpqky30","nombre":"Fecha","tipo":"LongDate","visibilidad":"private"},{"id":"druswoy","nombre":"Total","tipo":"BigDecimal","visibilidad":"private"}],"metodos":[]}],"relaciones":[{"id":"e_5llwz1x","origen":"c_ob42cxz","destino":"c_dioc1jg","tipo":"ASOCIACION","nombre":"","multiplicidadOrigen":"1","multiplicidadDestino":"0..*"}]}	inventario	4	2	t
2	2026-09-19 15:45:27.699212	2026-09-17 18:09:34.339478	{"clases":[{"id":"c_7pm52u4","nombre":"Cliente","estereotipo":"entidad","posicionX":-710.086482151491,"posicionY":-174.51148804567964,"atributos":[{"id":"saa3pxe","nombre":"ID","tipo":"Long","visibilidad":"private"},{"id":"ww5ll32","nombre":"Nombre","tipo":"String","visibilidad":"private"}],"metodos":[{"id":"ar3zar6","nombre":"actualizarDatos","tipoRetorno":"void","visibilidad":"public","parametros":[{"nombre":"param","tipo":"String"}]}]},{"id":"c_qa1hwts","nombre":"Pedido","estereotipo":"entidad","posicionX":-337.80244314073343,"posicionY":33.02054623614495,"atributos":[{"id":"ydjry71","nombre":"ID","tipo":"Long","visibilidad":"private"},{"id":"r0nd4kg","nombre":"Fecha","tipo":"LocalDate","visibilidad":"private"},{"id":"uklq1jt","nombre":"Total","tipo":"BigDecimal","visibilidad":"private"}],"metodos":[]},{"id":"1img4flj8","nombre":"NuevaClase","estereotipo":"","posicionX":-295.5779730027894,"posicionY":-479.3835933644847,"atributos":[],"metodos":[]},{"id":"dzrzgwx73","nombre":"Yango","estereotipo":"entidad","posicionX":-742.8140228332139,"posicionY":-481.28597597105045,"atributos":[{"id":"y2aq75grd","nombre":"ID","tipo":"String","visibilidad":"private"},{"id":"p9wv3l69b","nombre":"Dirreccion","tipo":"String","visibilidad":"private"}],"metodos":[]}],"relaciones":[{"id":"e_hy3a4db","origen":"c_7pm52u4","destino":"c_qa1hwts","tipo":"ASOCIACION","nombre":"","multiplicidadOrigen":"1","multiplicidadDestino":"0..*"}]}	personal	17	2	t
5	2026-09-21 14:24:29.951382	2026-09-21 14:24:29.951382	{"clases":[],"relaciones":[]}	veterinaria	0	2	t
\.


--
-- TOC entry 5139 (class 0 OID 106647)
-- Dependencies: 236
-- Data for Name: invitacion_proyecto; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.invitacion_proyecto (id, estado, fecha_creacion, fecha_expiracion, token, anfitrion_id, proyecto_id, usuario_invitado_id) FROM stdin;
1	ACEPTADA	2026-09-18 23:19:20.517716	2026-09-25 23:19:20.517716	a2eaca71-2f40-4994-86b0-8d7529825e53	1	1	3
4	PENDIENTE	2026-09-19 00:14:50.121512	2026-09-26 00:14:50.121512	36c07f3c-c6ea-4b7a-bd48-e2c4e7c61c9c	1	2	4
\.


--
-- TOC entry 5125 (class 0 OID 106508)
-- Dependencies: 222
-- Data for Name: participante_proyecto; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.participante_proyecto (id, activo, fecha_ingreso, proyecto_id, usuario_id) FROM stdin;
1	t	2026-09-18 22:47:11.751683	2	3
2	t	2026-09-18 23:21:36.718852	1	3
\.


--
-- TOC entry 5135 (class 0 OID 106598)
-- Dependencies: 232
-- Data for Name: permiso; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.permiso (id, activo, codigo, descripcion, nombre) FROM stdin;
1	t	GESTIONAR_USUARIOS	Permiso para gestionar usuarios	GESTIONAR USUARIOS
2	t	GESTIONAR_ROLES	Permiso para gestionar roles	GESTIONAR ROLES
3	t	GESTIONAR_PROYECTOS	Permiso para gestionar proyectos	GESTIONAR PROYECTOS
4	t	GESTIONAR_PARTICIPANTES	Permiso para gestionar participantes	GESTIONAR PARTICIPANTES
5	t	EDITAR_DIAGRAMAS	Permiso para editar diagramas	EDITAR DIAGRAMAS
6	t	CONSULTAR_BITACORA	Permiso para consultar bitacora	CONSULTAR BITACORA
7	t	GENERAR_BACKEND	Permiso para generar backend	GENERAR BACKEND
\.


--
-- TOC entry 5143 (class 0 OID 122951)
-- Dependencies: 240
-- Data for Name: peticion_ia; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.peticion_ia (id, exitoso, fecha_peticion, origen, prompt_texto, resultado_json, tokens_usados, diagrama_id, usuario_id) FROM stdin;
\.


--
-- TOC entry 5127 (class 0 OID 106517)
-- Dependencies: 224
-- Data for Name: proyecto; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.proyecto (id, activo, descripcion, fecha_actualizacion, fecha_creacion, nombre, anfitrion_id) FROM stdin;
2	t	es una prueba para ver si dan los diagramas	2026-09-18 13:03:38.877072	2026-09-17 18:09:20.507543	Biblioteca	1
1	t	Nuevo proyecto	2026-09-18 13:53:24.462847	2026-09-17 17:13:30.32248	Proyecto IA	1
\.


--
-- TOC entry 5129 (class 0 OID 106526)
-- Dependencies: 226
-- Data for Name: rol; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.rol (id, activo, descripcion, fecha_creacion, nombre) FROM stdin;
1	t	Administrador del sistema	2026-09-17 16:50:35.563491	ADMIN
2	t	Anfitrión de proyectos	2026-09-18 10:23:33.134716	ANFITRION
3	t	Colaborador de proyectos	2026-09-18 10:23:33.212866	COLABORADOR
4	t	entra para ver el diagrama 	2026-09-18 12:27:05.07369	CLIENTE
\.


--
-- TOC entry 5136 (class 0 OID 106608)
-- Dependencies: 233
-- Data for Name: rol_permiso; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.rol_permiso (rol_id, permiso_id) FROM stdin;
1	5
1	6
1	1
1	2
1	3
1	4
2	5
2	6
2	3
2	4
3	5
1	7
4	5
4	7
\.


--
-- TOC entry 5145 (class 0 OID 122964)
-- Dependencies: 242
-- Data for Name: sincronizacion; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.sincronizacion (id, estado_resolucion, fecha_colision, modelo_json_cliente, version_cliente, version_servidor, diagrama_id, usuario_id) FROM stdin;
\.


--
-- TOC entry 5131 (class 0 OID 106535)
-- Dependencies: 228
-- Data for Name: usuario; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.usuario (id, activo, apellido, correo, fecha_actualizacion, fecha_creacion, nombre, password, rol_id) FROM stdin;
4	t	Arispe	alejandro@gmail.com	2026-09-18 11:24:25.05832	2026-09-18 10:42:02.301588	Alejandro	$2a$10$BVVBx9aYT1683xL6/Gdy0evXznIoEZ4xBXiQriGRM1cxMMw29gZ6.	3
1	t	Sistema	admin@umlforge.com	2026-09-21 19:14:35.520478	2026-09-17 16:50:35.896804	Admin	$2a$10$zPKQFZt9U4DvhVEWP8sl5eLEIL9H/4YHpa3VFVC6Ikze/O7NK..0K	1
8	f	torrez	linda@gmail.com	2026-09-18 12:27:32.411899	2026-09-18 11:21:35.393172	linda	$2a$10$z1QMFnPmDWgaNA4MyYgls.4s3EJpxqQJMCOBawt9IdJ/MmqA17ZV2	4
3	t	Canaviri Mamani	alison@gmail.com	2026-09-18 22:16:07.903497	2026-09-18 10:30:09.488228	Alison Yesenia	$2a$10$jA7waUtNVY/2lN6RtWe99.TOimrfjYxxZ95xCnS4EuDqrNRQyX3p6	2
\.


--
-- TOC entry 5137 (class 0 OID 106627)
-- Dependencies: 234
-- Data for Name: usuario_permiso; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.usuario_permiso (usuario_id, permiso_id) FROM stdin;
1	5
1	6
1	7
1	1
1	2
1	3
1	4
8	5
8	7
8	4
3	6
3	4
3	3
3	5
3	1
3	2
3	7
\.


--
-- TOC entry 5151 (class 0 OID 0)
-- Dependencies: 237
-- Name: analisis_imagen_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.analisis_imagen_id_seq', 1, true);


--
-- TOC entry 5152 (class 0 OID 0)
-- Dependencies: 219
-- Name: bitacora_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.bitacora_id_seq', 186, true);


--
-- TOC entry 5153 (class 0 OID 0)
-- Dependencies: 229
-- Name: diagrama_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.diagrama_id_seq', 6, true);


--
-- TOC entry 5154 (class 0 OID 0)
-- Dependencies: 235
-- Name: invitacion_proyecto_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.invitacion_proyecto_id_seq', 4, true);


--
-- TOC entry 5155 (class 0 OID 0)
-- Dependencies: 221
-- Name: participante_proyecto_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.participante_proyecto_id_seq', 2, true);


--
-- TOC entry 5156 (class 0 OID 0)
-- Dependencies: 231
-- Name: permiso_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.permiso_id_seq', 7, true);


--
-- TOC entry 5157 (class 0 OID 0)
-- Dependencies: 239
-- Name: peticion_ia_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.peticion_ia_id_seq', 1, true);


--
-- TOC entry 5158 (class 0 OID 0)
-- Dependencies: 223
-- Name: proyecto_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.proyecto_id_seq', 4, true);


--
-- TOC entry 5159 (class 0 OID 0)
-- Dependencies: 225
-- Name: rol_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.rol_id_seq', 4, true);


--
-- TOC entry 5160 (class 0 OID 0)
-- Dependencies: 241
-- Name: sincronizacion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.sincronizacion_id_seq', 1, true);


--
-- TOC entry 5161 (class 0 OID 0)
-- Dependencies: 227
-- Name: usuario_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.usuario_id_seq', 11, true);


--
-- TOC entry 4950 (class 2606 OID 122949)
-- Name: analisis_imagen analisis_imagen_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.analisis_imagen
    ADD CONSTRAINT analisis_imagen_pkey PRIMARY KEY (id);


--
-- TOC entry 4920 (class 2606 OID 106506)
-- Name: bitacora bitacora_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bitacora
    ADD CONSTRAINT bitacora_pkey PRIMARY KEY (id);


--
-- TOC entry 4934 (class 2606 OID 106591)
-- Name: diagrama diagrama_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.diagrama
    ADD CONSTRAINT diagrama_pkey PRIMARY KEY (id);


--
-- TOC entry 4944 (class 2606 OID 106661)
-- Name: invitacion_proyecto invitacion_proyecto_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invitacion_proyecto
    ADD CONSTRAINT invitacion_proyecto_pkey PRIMARY KEY (id);


--
-- TOC entry 4922 (class 2606 OID 106515)
-- Name: participante_proyecto participante_proyecto_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.participante_proyecto
    ADD CONSTRAINT participante_proyecto_pkey PRIMARY KEY (id);


--
-- TOC entry 4936 (class 2606 OID 106607)
-- Name: permiso permiso_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.permiso
    ADD CONSTRAINT permiso_pkey PRIMARY KEY (id);


--
-- TOC entry 4952 (class 2606 OID 122962)
-- Name: peticion_ia peticion_ia_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.peticion_ia
    ADD CONSTRAINT peticion_ia_pkey PRIMARY KEY (id);


--
-- TOC entry 4926 (class 2606 OID 106524)
-- Name: proyecto proyecto_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.proyecto
    ADD CONSTRAINT proyecto_pkey PRIMARY KEY (id);


--
-- TOC entry 4940 (class 2606 OID 106614)
-- Name: rol_permiso rol_permiso_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rol_permiso
    ADD CONSTRAINT rol_permiso_pkey PRIMARY KEY (rol_id, permiso_id);


--
-- TOC entry 4928 (class 2606 OID 106533)
-- Name: rol rol_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rol
    ADD CONSTRAINT rol_pkey PRIMARY KEY (id);


--
-- TOC entry 4954 (class 2606 OID 122977)
-- Name: sincronizacion sincronizacion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sincronizacion
    ADD CONSTRAINT sincronizacion_pkey PRIMARY KEY (id);


--
-- TOC entry 4930 (class 2606 OID 106547)
-- Name: usuario uk2mlfr087gb1ce55f2j87o74t; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT uk2mlfr087gb1ce55f2j87o74t UNIQUE (correo);


--
-- TOC entry 4946 (class 2606 OID 106663)
-- Name: invitacion_proyecto uk6pu8thfpi4s2xgcr4j5abq6u0; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invitacion_proyecto
    ADD CONSTRAINT uk6pu8thfpi4s2xgcr4j5abq6u0 UNIQUE (proyecto_id, usuario_invitado_id);


--
-- TOC entry 4924 (class 2606 OID 106545)
-- Name: participante_proyecto uk7pmbppkffnq5bqp40dn21xwhx; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.participante_proyecto
    ADD CONSTRAINT uk7pmbppkffnq5bqp40dn21xwhx UNIQUE (proyecto_id, usuario_id);


--
-- TOC entry 4938 (class 2606 OID 106616)
-- Name: permiso uk8c7k3y09q0jf18cav2ahenq31; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.permiso
    ADD CONSTRAINT uk8c7k3y09q0jf18cav2ahenq31 UNIQUE (codigo);


--
-- TOC entry 4948 (class 2606 OID 106665)
-- Name: invitacion_proyecto ukg7qcg1lxvkbhmbn9by3jvb814; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invitacion_proyecto
    ADD CONSTRAINT ukg7qcg1lxvkbhmbn9by3jvb814 UNIQUE (token);


--
-- TOC entry 4942 (class 2606 OID 106633)
-- Name: usuario_permiso usuario_permiso_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario_permiso
    ADD CONSTRAINT usuario_permiso_pkey PRIMARY KEY (usuario_id, permiso_id);


--
-- TOC entry 4932 (class 2606 OID 106543)
-- Name: usuario usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_pkey PRIMARY KEY (id);


--
-- TOC entry 4969 (class 2606 OID 122978)
-- Name: analisis_imagen fk371qb2690c9q7usryfg3827ux; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.analisis_imagen
    ADD CONSTRAINT fk371qb2690c9q7usryfg3827ux FOREIGN KEY (proyecto_id) REFERENCES public.proyecto(id);


--
-- TOC entry 4962 (class 2606 OID 106622)
-- Name: rol_permiso fk6o522368i97la9m9cqn0gul2e; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rol_permiso
    ADD CONSTRAINT fk6o522368i97la9m9cqn0gul2e FOREIGN KEY (rol_id) REFERENCES public.rol(id);


--
-- TOC entry 4957 (class 2606 OID 106558)
-- Name: participante_proyecto fk710tcirhwvb1pqin2foornvwu; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.participante_proyecto
    ADD CONSTRAINT fk710tcirhwvb1pqin2foornvwu FOREIGN KEY (proyecto_id) REFERENCES public.proyecto(id);


--
-- TOC entry 4973 (class 2606 OID 122998)
-- Name: sincronizacion fk88hwn6g18tk8bm7ktgs9689va; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sincronizacion
    ADD CONSTRAINT fk88hwn6g18tk8bm7ktgs9689va FOREIGN KEY (diagrama_id) REFERENCES public.diagrama(id);


--
-- TOC entry 4955 (class 2606 OID 106553)
-- Name: bitacora fk8ycg8gp8rg9465qicdyd74wsf; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bitacora
    ADD CONSTRAINT fk8ycg8gp8rg9465qicdyd74wsf FOREIGN KEY (usuario_id) REFERENCES public.usuario(id);


--
-- TOC entry 4964 (class 2606 OID 106639)
-- Name: usuario_permiso fka3sdthyuceycy31ru6n0c2yyo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario_permiso
    ADD CONSTRAINT fka3sdthyuceycy31ru6n0c2yyo FOREIGN KEY (usuario_id) REFERENCES public.usuario(id);


--
-- TOC entry 4974 (class 2606 OID 123003)
-- Name: sincronizacion fkc01dqexl1bc4njjs4qqra5hpj; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sincronizacion
    ADD CONSTRAINT fkc01dqexl1bc4njjs4qqra5hpj FOREIGN KEY (usuario_id) REFERENCES public.usuario(id);


--
-- TOC entry 4956 (class 2606 OID 106548)
-- Name: bitacora fkc95qgnr0ntfdvsfd0mi00e7ws; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bitacora
    ADD CONSTRAINT fkc95qgnr0ntfdvsfd0mi00e7ws FOREIGN KEY (proyecto_id) REFERENCES public.proyecto(id);


--
-- TOC entry 4966 (class 2606 OID 106676)
-- Name: invitacion_proyecto fkd6oxjg46uy3r96vaxem2si241; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invitacion_proyecto
    ADD CONSTRAINT fkd6oxjg46uy3r96vaxem2si241 FOREIGN KEY (usuario_invitado_id) REFERENCES public.usuario(id);


--
-- TOC entry 4958 (class 2606 OID 106563)
-- Name: participante_proyecto fkeruiumg7a7yoj51dvfqg5gljd; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.participante_proyecto
    ADD CONSTRAINT fkeruiumg7a7yoj51dvfqg5gljd FOREIGN KEY (usuario_id) REFERENCES public.usuario(id);


--
-- TOC entry 4963 (class 2606 OID 106617)
-- Name: rol_permiso fkfyao8wd0o5tsyem1w55s3141k; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rol_permiso
    ADD CONSTRAINT fkfyao8wd0o5tsyem1w55s3141k FOREIGN KEY (permiso_id) REFERENCES public.permiso(id);


--
-- TOC entry 4970 (class 2606 OID 122983)
-- Name: analisis_imagen fkn0juav8yarapydd86liomxnfe; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.analisis_imagen
    ADD CONSTRAINT fkn0juav8yarapydd86liomxnfe FOREIGN KEY (usuario_id) REFERENCES public.usuario(id);


--
-- TOC entry 4965 (class 2606 OID 106634)
-- Name: usuario_permiso fkndrkj5wx5bxhw6b3gdmvmym2i; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario_permiso
    ADD CONSTRAINT fkndrkj5wx5bxhw6b3gdmvmym2i FOREIGN KEY (permiso_id) REFERENCES public.permiso(id);


--
-- TOC entry 4959 (class 2606 OID 106568)
-- Name: proyecto fko6emd66cpsqxwa47yls1vd169; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.proyecto
    ADD CONSTRAINT fko6emd66cpsqxwa47yls1vd169 FOREIGN KEY (anfitrion_id) REFERENCES public.usuario(id);


--
-- TOC entry 4971 (class 2606 OID 122993)
-- Name: peticion_ia fkokox53xbu9w0rr2j4okt0eodg; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.peticion_ia
    ADD CONSTRAINT fkokox53xbu9w0rr2j4okt0eodg FOREIGN KEY (usuario_id) REFERENCES public.usuario(id);


--
-- TOC entry 4972 (class 2606 OID 122988)
-- Name: peticion_ia fkqaols2s5w9gept4xbt65js0rs; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.peticion_ia
    ADD CONSTRAINT fkqaols2s5w9gept4xbt65js0rs FOREIGN KEY (diagrama_id) REFERENCES public.diagrama(id);


--
-- TOC entry 4967 (class 2606 OID 106671)
-- Name: invitacion_proyecto fkr1o9b5pffrbld0sn0j4fliktb; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invitacion_proyecto
    ADD CONSTRAINT fkr1o9b5pffrbld0sn0j4fliktb FOREIGN KEY (proyecto_id) REFERENCES public.proyecto(id);


--
-- TOC entry 4960 (class 2606 OID 106573)
-- Name: usuario fkshkwj12wg6vkm6iuwhvcfpct8; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT fkshkwj12wg6vkm6iuwhvcfpct8 FOREIGN KEY (rol_id) REFERENCES public.rol(id);


--
-- TOC entry 4961 (class 2606 OID 106592)
-- Name: diagrama fksmx8a32qo8iotrwkmg1u3f297; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.diagrama
    ADD CONSTRAINT fksmx8a32qo8iotrwkmg1u3f297 FOREIGN KEY (proyecto_id) REFERENCES public.proyecto(id);


--
-- TOC entry 4968 (class 2606 OID 106666)
-- Name: invitacion_proyecto fkufyjme6g7l364e03e93sfsj3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invitacion_proyecto
    ADD CONSTRAINT fkufyjme6g7l364e03e93sfsj3 FOREIGN KEY (anfitrion_id) REFERENCES public.usuario(id);


-- Completed on 2026-09-21 19:29:20

--
-- PostgreSQL database dump complete
--

\unrestrict 29GBjWIChDLUofhmfaZj3iw1ZeExSJ5x6KTLitnd2ej0yPOB6RUnK8q68A4WmRG

