package com.umlforge.backend.service.codegen.flutter;

import org.springframework.stereotype.Component;
import com.umlforge.backend.dto.UmlModelDto.UmlClass;
import java.util.List;
import java.util.stream.Collectors;

@Component
public class FlutterStructureGenerator {

    public String generatePubspec() {
        return """
name: umlforge_generated_app
description: Flutter application generated by UMLForge-AI
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
""";
    }

    public String generateReadme() {
        return """
# Aplicación Móvil Generada (Flutter)

Este proyecto fue generado de forma 100% dinámica por UMLForge-AI basado en tu diagrama UML.

## 1. Configuración del Backend

La URL de conexión de la API se encuentra en el archivo:
`lib/api_config.dart`

Dependiendo del entorno donde ejecutes esta aplicación, la URL debe cambiar:
- **Ejemplo Android Emulator**: `http://10.0.2.2:8081/api`
- **Ejemplo Flutter Web**: `http://localhost:8081/api`
- **Dispositivo Físico**: Deberás usar la IP local de tu computadora en la red Wi-Fi (ej. `http://192.168.1.15:8081/api`).

Asegúrate de configurar esto según el entorno de pruebas.

---

## 2. Preparación del Proyecto Flutter

Al descomprimir este ZIP, abre tu terminal y ejecuta los siguientes comandos:

1. **Entrar al proyecto**:
   ```bash
   cd umlforge-generated-mobile
   ```

2. **Generar las carpetas nativas (Android/iOS/Web)**:
   Como esta es una estructura base, necesitas crear la estructura nativa ejecutando:
   ```bash
   flutter create .
   ```
   Esto generará las carpetas `android/`, `ios/`, `web/`, entre otras.

3. **Instalar dependencias**:
   ```bash
   flutter pub get
   ```

4. **Analizar errores**:
   ```bash
   flutter analyze
   ```
   (Debería mostrar "No issues found!").

---

## 3. Si no cuenta con Android Studio o un emulador

Para verificar qué dispositivos tienes disponibles en tu sistema, ejecuta:
```bash
flutter devices
```

Si solamente aparecen navegadores o aplicaciones de escritorio como:
- Chrome
- Edge
- Windows

Deberás **instalar Android Studio** y crear un **dispositivo virtual (AVD)** para poder probar la aplicación en formato celular.

---

## 4. Ejecutar la Aplicación

Puedes lanzar la aplicación en los distintos dispositivos conectados:

- **Ejecutar normalmente (selecciona el primero disponible)**:
  ```bash
  flutter run
  ```
- **Ejecutar en navegador (Web)**:
  ```bash
  flutter run -d chrome
  ```
- **Ejecutar en Android**:
  ```bash
  flutter run -d android
  ```

---

## 5. Generar APK para Instalar en Celular

Para generar una aplicación instalable de Android (Release Mode), ejecuta:
```bash
flutter build apk --release
```

El archivo generado estará ubicado en la siguiente ruta:
`build/app/outputs/flutter-apk/app-release.apk`

**Para instalar:**
1. Copiar el archivo `.apk` a tu dispositivo Android (vía USB, Google Drive, WhatsApp, etc.).
2. Abrir el archivo desde el explorador de archivos del celular.
3. Permitir la instalación de aplicaciones de orígenes externos si Android lo solicita.
""";
    }

    public String generateApiConfig() {
        return """
class ApiConfig {
  // Cambiar esta URL a la IP de tu computadora si ejecutas en un dispositivo físico.
  // 10.0.2.2 es para acceder a localhost desde el emulador de Android.
  static const String baseUrl = 'http://10.0.2.2:8081/api';
}
""";
    }

    public String generateMain(List<UmlClass> classes) {
        StringBuilder sb = new StringBuilder();
        sb.append("import 'package:flutter/material.dart';\n");
        
        for (UmlClass umlClass : classes) {
            String className = capitalize(umlClass.nombre());
            sb.append("import 'screens/").append(className.toLowerCase()).append("_list_screen.dart';\n");
        }
        
        sb.append("\nvoid main() {\n");
        sb.append("  runApp(const MyApp());\n");
        sb.append("}\n\n");
        
        sb.append("class MyApp extends StatelessWidget {\n");
        sb.append("  const MyApp({super.key});\n\n");
        
        sb.append("  @override\n");
        sb.append("  Widget build(BuildContext context) {\n");
        sb.append("    return MaterialApp(\n");
        sb.append("      title: 'UMLForge App',\n");
        sb.append("      theme: ThemeData(\n");
        sb.append("        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),\n");
        sb.append("        useMaterial3: true,\n");
        sb.append("      ),\n");
        
        if (classes != null && !classes.isEmpty()) {
            String firstClass = capitalize(classes.get(0).nombre());
            sb.append("      home: const ").append(firstClass).append("ListScreen(),\n");
        } else {
            sb.append("      home: const Scaffold(body: Center(child: Text('No hay clases'))),\n");
        }
        
        sb.append("    );\n");
        sb.append("  }\n");
        sb.append("}\n");
        
        return sb.toString();
    }
    
    private String capitalize(String str) {
        if (str == null || str.isEmpty()) return str;
        String name = str.replaceAll("\\s+", "");
        return name.substring(0, 1).toUpperCase() + name.substring(1);
    }
}
